[project]
name = "gibdd"
version = "0.1.0"
description = "Educational project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "requests>=2.32.4",
]